### ISSUE TITLE
[Bug - models] Custom head models don't render in the inventory

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Model_Features#150]
**Bug Description**
When attempting to render any custom head model apart from the dragon head, notably only in item form, the game immediately crashes.

**To Reproduce**
1. Install [this](https://github.com/Traben-0/Entity_Model_Features/files/13691225/MickeyJoesBarelyDefault_V10.1-mre.zip) resourcepack example based on [Mickey Joe's Barely Default](https://www.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default)
2. Search for any broken mob head in the creative inventory (note the pack doesn't include a creeper head model)
3. Observe crash

**Expected behavior**
The game should not crash, and instead should render the correct custom model

**Crashlog**
Can be found in the Discord

**System**
 - Minecraft Version: 1.20.2
 - EMF version 1.2
 - Does the issue persist with only EMF installed? Yes (plus ETF and Fabric API)

**Comment by Traben-0** [comment]
I've identified the cause, and prevented the crash, this fix may affect texture overrides in skull blocks in inventory until I look into it further

**Comment by Batcho001** [comment]
I don't know if I have the same issue as Thanos, but I am crashing because of the skeleton_skull item. In the crash log it mentions that it may be my immediately fast mod or gecko lib but I've already tried it without either of them and it still crashes. I found out that it only crashes with EMF enabled. Here is my crash log:
[crash-2023-12-22_14.44.26-client.txt](https://github.com/Traben-0/Entity_Model_Features/files/13756664/crash-2023-12-22_14.44.26-client.txt)

**Comment by Traben-0** [comment]
Similar issue which I've also fixed for next update

**Comment by Batcho001** [comment]
Your great man, thanks. I'll patiently wait for the next update and thanks for the quick reply.

**Comment by GeekyBakerBen** [comment]
Can confirm this only happens in the newest version so for anyone struggling with this crash while waiting on the next update, just roll back to the previous version for now and all should be ok.
