### ISSUE TITLE
[Bug] Incompatible with Embeddium

### ISSUE THREAD

**Issue by Busyfox123** [Traben-0/Entity_Model_Features#154]
Minecraft version：1.20.1
forge:47.2.0
[1.20.1] Embeddium 0.2.16
EMF] Entity Model Features[Forge 1.20.1] 1.1.0
Tested in environments with only Embeddium, EMF, and Oculus
Wearing armor from other mods while using Embeddium can cause a significant decrease in frame rate
When using a third person perspective or looking at other players, if the opponent is wearing armor, the frame rate will significantly decrease
Deleting Embeddium will not cause this issue
When the shader is not loaded, the frame rate will also be significantly reduced

test mod:
Obscure API
Aquamirae 6 API15 (1.20.1)
twilightforest-1.20.1-4.3.1893-universal

spark:
https://spark.lucko.me/Lb3B3zs2qX
基于Spark概要文件，滞后似乎来自EMF的代码。
![2023-12-27_22 37 27](https://github.com/Traben-0/Entity_Model_Features/assets/117924192/0d51f5aa-1c3c-4c66-814f-14b3c2d816e4)
![2023-12-27_22 37 43](https://github.com/Traben-0/Entity_Model_Features/assets/117924192/21fbfa76-3597-47d6-bdd7-27c8d73e0819)
![2023-12-26_23 55 29](https://github.com/Traben-0/Entity_Model_Features/assets/117924192/c031cf34-3114-48f9-bbef-870e01f8367f)
![2023-12-26_23 55 45](https://github.com/Traben-0/Entity_Model_Features/assets/117924192/e9b9fd58-b1da-460c-8711-f595a5c2abae)

**Comment by kakashi1464** [comment]
tried without oculus?

**Comment by TBlazeWarriorT** [comment]
OH, so this is what was lagging me...
Title is a bit misleading, I'd just call it laggy not incompatible
> tried without oculus?

I just tried it too, still lags without oculus, which was expected since it was lagging without shaders too before fully disabling oculus
I didn't try without Embeddium, but can confirm removing EMF massively improves my framerate from 15 when looking at 8 armor stands to 150. It seems like when this bug is being triggered, your FPS gets roughly divided by the amount of armor sets on the screen... A single armor stand with modded armor takes me from 150 to 75, and vanilla armor doesn't lag

**Comment by TBlazeWarriorT** [comment]
Seems fixed in EMF 1.2.1
![image](https://github.com/Traben-0/Entity_Model_Features/assets/25572454/24193c75-42fc-48c4-b744-cca64ac22543)
