### ISSUE TITLE
CRASH on startup "IncompatibleClassChangeError" - (fix known)

### ISSUE THREAD

**Issue by MFNmodding** [Traben-0/Entity_Model_Features#23]
**Describe the bug**
the game crashes right at the end of the loading sequence and "java.lang.IncompatibleClassChangeError: class traben.entity_model_features.models.EMFModelPart3 cannot inherit from final class net.minecraft.client.model.geom.ModelPart" appears at the top of the crash log.

**To Reproduce**
1. start the game
2. wait for it to finish loading until just after the loading screen fades and just before the title screen shows up
3. notice that you're viewing the launcher again.

**Expected behavior**
i expected to be able to use the modpack and not be forced to only view the loading screen and launcher.

**Screenshots**

**Crashlog**
(https://pastebin.com/VviqXJyu)

**(please complete the following information):**
 -mc1.19.3
 -emf 0.2.5
 - it does not, but i don't know which mod is causing it.

**Additional context**

**Comment by Traben-0** [comment]
can i get your mod list?

**Comment by Traben-0** [comment]
I have identified the issue and its actually not EMF's fault

Whenever forge force crashes the game because you are missing a required mod dependency for any mod, it will somehow break EMFs class loading after that step and the resulting crash report will blame EMF instead of the missing/ outdated dependency

if you look at your actual game log (NOT the crash report) you will see a crash reason given higher up in the log you can search for it with the keyword "FATAL" it likely mentions a missing or outated dependency

I will see if i can prevent forge from blaming/breaking EMF when this happens

**Comment by Traben-0** [comment]
I have identified how to prevent the crash from incorrectly blaming EMF the fix will be in the next bugfix version 0.2.6 likely out tomorrow

**Comment by MFNmodding** [comment]
thank you, hopefully i will figure out which mod is messing with things.

**Comment by Traben-0** [comment]
if you get your full log and search for "FATAL" you will see the dependancy message next to the FATAL error

**Comment by MFNmodding** [comment]
alright i found it. apparently ars magica legacy is not supposed to be in 1.19.3, despite it being available for that version. kinda annoying but i'll live.

**Comment by Traben-0** [comment]
perfect, leave the issue open for the time being I will close it when i release the patch

**Comment by RaptaG** [comment]
Unpin maybe?

**Comment by Traben-0** [comment]
oh i thought closing it would do that

**Comment by RaptaG** [comment]
Nope

**Comment by RaptaG** [comment]
Nice
