### ISSUE TITLE
[Feature Request] Send identification packet to servers on login

### ISSUE THREAD

**Issue by DaniDipp** [Traben-0/Entity_Model_Features#300]
**Is your feature request related to a problem? Please describe.**
I maintain an EMF and a vanilla version of my server resource pack. Currently, I send the EMF version by default and when users complain about broken models, they can use a command to opt out and use the vanilla version.
This may be detrimental to the new-player experience.

**Describe the solution you'd like**
If the mod identifies itself by sending a packet to the server upon login, I can automatically send users the correct resourcepack.

**Does OptiFine do this**
Optifine supports client branding when installed standalone, but doesn't do plugin messaging when installed with a mod loader ([yet](https://github.com/sp614x/optifine/issues/1631))

**Comment by Traben-0** [comment]
This is not planned, its a bit out of scope and is more of a thing for the loader to handle, such as forge already does.

Is it not possible for you to format the pack so that vanilla users are unaffected?

there are zero things in EMF that cannot be structured this way to support both vanill and EMF users seperately
